# Generated by Django 2.2.5 on 2019-09-10 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='Full_name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='message',
        ),
        migrations.AddField(
            model_name='gym',
            name='contact_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
